ELM_BRANCH: E3SM_v2.0_fates_with_var_soil_thick
ELM_REMOTE: git@github.com:rutujact/E3SM.git
LOG_DIR: log
OUTPUT_DIR: output
PARAM_DIR: params
DATA_DIR: data
CASE_DIR: CASE_DIR
ELM_RUN_PY: src/parallel.run.py
TAG: drm.test.1.E3SMv2
COMPSET: IELMFATES
MACHINE: badger
STOP_N: 2
REST_N: 1
RUN_STARTDATE: 2010-01-01
DATM_CLMNCEP_YR_START: 2010
DATM_CLMNCEP_YR_END: 2015
PARAM_FILE:
  DOMAIN: domain_bci_panama_v1_c171113.nc
  SURF: surfdata_bci_panama_v1_c171113.3563.nc
  ELM: elm_parameter_file_name.3563.nc
CLONE_BASE:
  SURF: surfdata_bci_panama_v1_c171113.
CLONE_TYPE:
- SURF
CLIM_DATA_DIR: bci_0.1x0.1_v4.0i
CLIM_DATA: bci_0.1x0.1_met.v4_pio2
SENSITIVITY: true
SITES_PARAM_TABLE_PATH: data/HPU.Table.csv
BUILD_PARAM_TABLE: true
GIVEN_PARAM_TABLE_PATH: data/Param.Table.csv
BUILT_PARAM_TABLE_PATH: output/Param.Table.csv
RANGE:
  PARAMETERS:
  - aveDTB
  - FMAX
  MINPARAM:
  - 0
  - 0.01
  MAXPARAM:
  - 18
  - 0.8
SLICES: 10
PARAM_KEY:
  SURF:
  - aveDTB
  - FMAX
MUTATE: true
SIM_ID_START: 1
SIM_ID_END: 2
ACCOUNT: w22_fire
N_NODE: 1
N_CPU_PER_NODE: 36
WALL_TIME: 3600
OUTPUT_TYPE: csv
