ELM_BRANCH: E3SMv2.0_chicoma_re-ported_12Jan2023
ELM_REMOTE: git@github.com:rutujact/E3SM.git
FATES_BRANCH: rutujact_IO_DRM_Hydro_sci.1.58.1_api.24.1.0
FATES_REMOTE: git@github.com:rutujact/fates.git
LOG_DIR: log
OUTPUT_DIR: output
VDM2FM_DIR: VDM2FM
FM2VDM_DIR: FM2VDM
CASE_DIR: CASE_DIR
ELM_RUN_PY: src/parallel.run.py
TAG: drm.FATES.api24.12.1.1.0.5_3
COMPSET: IELMFATES
HYDRO: false
NOHYDROFUELMOISTURE: 0.5
MACHINE: chicoma
COMPILER: gnu
RUN_STARTDATE: 1990-01-01
REST_DATE: 19910101
DATM_CLMNCEP_YR_START: 1990
DATM_CLMNCEP_YR_END: 1990
FINAL_TAG_YEAR: 1991
NMONTHS: 12
NCYCYEAR: 1
NCYCLE: 1
STOP_N: 1
REST_N: 1
CYCLE_INDEX: 1
FINALTAG_MONTH_CI0: 12
DOMAIN_DIR: params
DOMAIN_FILE: domain_eglin_c210813.nc
SURF_DIR: params
SURF_FILE: surfdata_eglin_c210813.nc
PARAM_ELM_DIR: params
PARAM_ELM_FILE: elm_parameter_file_name.3563.nc
PARAM_FATES_DIR: params
PARAM_FATES_FILE: FL_eglin800.nc
IC_DATA_DIR: data/eglin_0.1x0.1_v4.0i
CLIM_DATA_DIR: data/eglin_0.1x0.1_v4.0i/eglin_0.1x0.1_met.v2pio
CLONE_BASE:
  SURF: surfdata_eglin_c210813.
FILE_TYPE_TO_CLONE:
  LIST:
  - SURF
SENSITIVITY: true
SITES_PARAM_TABLE_PATH: data/HPU.Table.csv
BUILD_PARAM_TABLE: true
GIVEN_PARAM_TABLE_PATH: data/Param.Table.csv
BUILT_PARAM_TABLE_PATH: output/Param.Table.csv
MAXPFT: 3
RANGE:
  PARAMETERS:
  - FMAX
  MINPARAM:
  - 0.01
  MAXPARAM:
  - 0.8
SLICES: 25
PARAM_KEY:
  SURF:
  - FMAX
MUTATE: false
FIRE_RES: 400
FATES_RES: 200
SIM_ID_START: 1
SIM_ID_END: 4
ACCOUNT: w22_fire
N_NODE: 1
N_CPU_PER_NODE: 256
WALL_TIME: 00:05:00
OUTPUT_TYPE: csv
