#-----------------------------------------------------
#ELM Model Configuration # (add more specific info in this later)
#------------------------------------------#
PROJECT_ROOT: '/turquoise/usr/projects/veg/cxu/ACME_cases/DRToyModel'
LOG_PATH: '/turquoise/usr/projects/veg/cxu/ACME_cases/DRToyModel/log'
OUTPUT_DIR: '/lustre/scratch3/turquoise/cxu/ACME/cases/DRToyModel'
OUTPUT_TYPE: 'csv' 
CASE_BASE: 'TEST.HPU'
HPU_PATH: 'HPU.Table' 
HPU_ID_START: 1
HPU_ID_END: 2
DURATION: 10 
ELM:
  parameters:
    SandPCT: 5
    SiltPCT: 10
    LakePCT: 1
VEG:
  parameters:
     Vcmax: 50
     SLA: 0.02
