#-----------------------------------------------------
#ELM Model Configuration # (add more specific info in this later)
#------------------------------------------#

# ----ELM-FATES code----
ELM_BRANCH: rutuja/ELM_FATES_HYDRO_DFLT_pedotrf_HKSAT_ADJ
FATES_BRANCH: xuchongang/coastal_veg_ready_to_merge_July_2019
ELM_REMOTE: git@github.com:rutujact/E3SM.git
FATES_REMOTE: git@github.com:xuchongang/fates.git

# ----Directories under PROJECT ROOT----
LOG_DIR: log
OUTPUT_DIR: output 
PARAM_DIR: params 
DATA_DIR: data
CASE_DIR: CASE_DIR
ELM_RUN_PY: src/parallel.run.py

#----Create exact ELM clones or vary parameter files----
MUTATE: FALSE

#----ELM parameter ensemble data----
HPU_PATH: data/HPU.Table.csv

#----Is the parameter enseble for a sensitivity analysis?----
SENSITIVITY: FALSE

#----Ensemble IDs to run---- 
HPU_ID_START: 1
HPU_ID_END: 2 

#----ELM case set-up attributes----
TAG: HPU.TEST
COMPSET: ICLM45ED
MAC: badger
COMPILER: intel
STOP_N: 2 # years to run
REST_N: 2 # frequency of yrs to write restart file
RUN_STARTDATE: 2017-01-01
DATM_CLMNCEP_YR_START: 2017
DATM_CLMNCEP_YR_END: 2018
SURF_BASE: surfdata_bci_panama_v1_c171113.
DOMAIN_FILE: domain_bci_panama_v1_c171113.nc
SURF_FILE: surfdata_bci_panama_v1_c171113.1.nc
FATES_PARAM: fates_params_default_2pft.nc
ELM_PARAM: elm_parameter_file_name1.nc
CLIM_DATA_DIR: bci_0.1x0.1_v4.0i
CLIM_DATA: bci_0.1x0.1_met.v5.1

#----ELM Run attributes----
N_NODE: 1 # Make sure that N_NODE*N_CPU_PER_NODE >= (HPU_ID_END-HPU_ID_START)+1
N_CPU_PER_NODE: 36
WALL_TIME: 1:00:00
OUTPUT_TYPE: csv
