#-----------------------------------------------------
#ELM Model Configuration # (add more specific info in this later)
#------------------------------------------#

# ----ELM-FATES code----
ELM_BRANCH: rutuja/ELM_FATES_HYDRO_DFLT_pedotrf_HKSAT_ADJ
FATES_BRANCH: rutuja/xuc/coastal_veg_ready_to_merge_July_2019
ELM_REMOTE: git@github.com:rutujact/E3SM.git
FATES_REMOTE: git@github.com:rutujact/fates.git

# ----Directories under PROJECT ROOT----
LOG_DIR: log
OUTPUT_DIR: output 
PARAM_DIR: params 
DATA_DIR: data
CASE_DIR: CASE_DIR
ELM_RUN_PY: src/parallel.run.py

#----Create exact ELM clones or mutate/vary parameter files----
MUTATE: TRUE

#----ELM parameter ensemble data across sites----
SITES_PARAM_PATH: data/HPU.Table.csv

#----Is the parameter enseble for a sensitivity analysis?----
SENSITIVITY: TRUE # This turns off multi-site runs 
SEN_PATH: output/Param.Table.csv # output file
RANGE: 
  PARAMETERS: 
    - fates_rootb_par
  MINPARAM:
    - 0.217
  MAXPARAM:
    - 1.956
SLICES: 10

#----Ensemble IDs to run---- 
SIM_ID_START: 1
SIM_ID_END: 4 

#----ELM case set-up attributes----
TAG: BCI.test
COMPSET: ICLM45ED
MAC: badger
COMPILER: intel
STOP_N: 2 # years to run
REST_N: 10 # frequency of yrs to write restart file
RUN_STARTDATE: 1971-01-01
DATM_CLMNCEP_YR_START: 1971
DATM_CLMNCEP_YR_END: 2020
PARAM_FILE:
  DOMAIN: domain_bci_panama_v1_c171113.nc
  SURF: surfdata_bci_panama_v1_c171113.3563.nc
  FATES: fates_parameter_file_name.3563.nc
  ELM: elm_parameter_file_name.3563.nc
CLONE_BASE: fates_parameter_file_name. # base file to clone
CLONE_TYPE: FATES # parameter file type to change
CLIM_DATA_DIR: bci_0.1x0.1_v4.0i
CLIM_DATA: bci_0.1x0.1_met.v6.1

#----ELM Run attributes----
N_NODE: 1 # Make sure that N_NODE*N_CPU_PER_NODE >= (HPU_ID_END-HPU_ID_START)+1
N_CPU_PER_NODE: 36
WALL_TIME: 1:00:00
OUTPUT_TYPE: csv
