#-----------------------------------------------------
#ELM Model Configuration # (add more specific info in this later)
#------------------------------------------#
PROJECT_ROOT: /turquoise/usr/projects/veg/rutuja/ACME_cases/ELM_Disease
RUN_ROOT: /lustre/scratch3/turquoise/rutuja/ACME/cases
# Directories under PROJECT_ROOT----
LOG_DIR: log
OUTPUT_DIR: output 
PARAM_DIR: params 
DATA_DIR: data
CASE_DIR: CASE_DIR
ELM_RUN_PY: src/parallel.run.py

#----Create exact ELM clones or vary parameter files----
MUTATE: FALSE

#----ELM parameter ensemble data----
HPU_PATH: data/HPU.Table.csv

#----Ensemble IDs to run---- 
HPU_ID_START: 1
HPU_ID_END: 2 

#----ELM case set-up attributes----
TAG: HPU.TEST
COMPSET: ICLM45ED
MAC: badger
COMPILER: intel
STOP_N: 2 # years to run
REST_N: 2 # frequency of yrs to write restart file
RUN_STARTDATE: 2017-01-01
DATM_CLMNCEP_YR_START: 2017
DATM_CLMNCEP_YR_END: 2018
SURF_BASE: surfdata_bci_panama_v1_c171113.

#----ELM Run attributes----
N_NODE: 1 # Make sure that N_NODE*N_CPU_PER_NODE >= (HPU_ID_END-HPU_ID_START)+1
N_CPU_PER_NODE: 36
WALL_TIME: 1:00:00
OUTPUT_TYPE: csv
